generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AccountEntry
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          account_entry
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [date, Account, amount, description]
      filter:  ~
      form:    
        display: [date, account_id, amount, description, notes]
      edit:    ~
      new:     ~
