generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Record
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          record
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    
        display: [_picture,_employee_name, datetime, is_valid, filename]
      edit:    ~
      new:     ~
